[package]
name = "ie"
version = "0.1.0"
edition = "2018"

[workspace]

[dependencies]
json = "0.12.4" 
macroquad = "0.3"
egui-macroquad = "0.6.1"
egui = "0.14.2"
lazy_static = "1.4.0"
hashbrown = "0.11"

[dependencies.pyo3]
version = "0.14.5"
features = ["auto-initialize"]